# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_auto_20161107_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theater',
            options={'ordering': ('state', 'city', 'name')},
        ),
        migrations.AddField(
            model_name='film',
            name='theaters',
            field=models.ManyToManyField(to='films.Theater'),
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.Genre'),
        ),
    ]
