# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_auto_20161109_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='theater',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='films.Genre'),
        ),
        migrations.AlterField(
            model_name='film',
            name='theaters',
            field=models.ManyToManyField(blank=True, to='films.Theater'),
        ),
        migrations.AlterField(
            model_name='film',
            name='year_prod',
            field=models.IntegerField(blank=True),
        ),
    ]
