# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_auto_20161112_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='films',
            field=models.ManyToManyField(blank=True, to='films.Film'),
        ),
    ]
