# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 03:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_theater_films'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theater',
            name='films',
        ),
    ]
