# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_auto_20161114_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theater',
            name='num_screens',
            field=models.IntegerField(blank=True),
        ),
    ]
