version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: djangorestframework
    versions:
    - 3.12.3
  - dependency-name: django
    versions:
    - 3.1.5
    - 3.1.6
